apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec: 
  ports:
    - port: 5001            # Expose the service on port 5001
      targetPort: 5001      # Redirect traffic to port 5001 in the container
      protocol: TCP
  type: ClusterIP           # The service is accessible only within the cluster
  selector:
    role: api               # This selector targets pods with the label 'role: api'
