services:
  database:
    build: ./db
    image: database:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quotesdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./quotesAPI
    image: backend:latest
    container_name: backend
    restart: always
    depends_on:
      - database
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=quotesdb;User=root;Password=root;
    ports:
      - "5001:5001"

  frontend:
    build: ./app
    image: frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5002:5002"

volumes:
  db_data:
