apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv  # Changed from mongo-pv to mysql-pv
  namespace: three-tier  # Keeping the same namespace
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/mysql  # Changed from /data/db to MySQL's default data directory
