apiVersion: v1
kind: Service
metadata:
  namespace: workshop
  name: mysql-svc  # Changed from mongodb-svc to mysql-svc
spec:
  selector:
    app: mysql  # Updated to match MySQL deployment label
  ports:
    - name: mysql
      protocol: TCP
      port: 3306  # MySQL runs on port 3306
      targetPort: 3306
