apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workshop  # Update to the correct namespace
spec:
  ports:
    - port: 5002               # Expose the service on port 5002
      targetPort: 5002         # Redirect traffic to port 5002 in the container
      protocol: TCP
  type: LoadBalancer            # Expose the service externally
  selector:
    role: frontend  
