version: '3.9'

services:
  db:
    container_name: quotes-db
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quotesdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  backend:
    container_name: quotes-api
    build: ./quotesAPI  # This is your new .NET backend folder
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=quotesdb;User=user;Password=password;"
    ports:
      - "5001:5001"

  frontend:
    container_name: quotes-frontend
    build: ./app  # Your Flask frontend
    depends_on:
      - backend
    ports:
      - "5002:5002"

volumes:
  db-data:
